package com.deppon.nhr.module.remote.fssc.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.13
 * 2014-03-19T13:59:57.125+08:00
 * Generated source version: 2.6.13
 * 
 */
@WebService(targetNamespace = "http://www.deppon.com/nhr/module/remote/fssc/service", name = "PersonalLoanService")
@XmlSeeAlso({com.deppon.nhr.module.remote.fssc.shared.domain.personalloan.ObjectFactory.class, com.deppon.esb.header.ObjectFactory.class, com.deppon.esb.exception.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface PersonalLoanService {

    @WebResult(name = "loanAmountResponse", targetNamespace = "http://www.deppon.com/nhr/module/remote/fssc/shared/domain/personalloan", partName = "loanAmountResponse")
    @WebMethod(action = "http://www.deppon.com/nhr/module/remote/fssc/service/addLoanAmount")
    public com.deppon.nhr.module.remote.fssc.shared.domain.personalloan.LoanAmountResponse addLoanAmount(
        @WebParam(partName = "loanAmountRequest", name = "loanAmountRequest", targetNamespace = "http://www.deppon.com/nhr/module/remote/fssc/shared/domain/personalloan")
        com.deppon.nhr.module.remote.fssc.shared.domain.personalloan.LoanAmountRequest loanAmountRequest,
        @WebParam(partName = "esbHeader", mode = WebParam.Mode.INOUT, name = "esbHeader", targetNamespace = "http://www.deppon.com/esb/header", header = true)
        javax.xml.ws.Holder<com.deppon.esb.header.ESBHeader> esbHeader
    ) throws CommonException;

    @WebResult(name = "loanStatusResponse", targetNamespace = "http://www.deppon.com/nhr/module/remote/fssc/shared/domain/personalloan", partName = "loanStatusResponse")
    @WebMethod(action = "http://www.deppon.com/nhr/module/remote/fssc/service/queryLoanStatus")
    public com.deppon.nhr.module.remote.fssc.shared.domain.personalloan.LoanStatusResponse queryLoanStatus(
        @WebParam(partName = "loanStatusRequest", name = "loanStatusRequest", targetNamespace = "http://www.deppon.com/nhr/module/remote/fssc/shared/domain/personalloan")
        com.deppon.nhr.module.remote.fssc.shared.domain.personalloan.LoanStatusRequest loanStatusRequest,
        @WebParam(partName = "esbHeader", mode = WebParam.Mode.INOUT, name = "esbHeader", targetNamespace = "http://www.deppon.com/esb/header", header = true)
        javax.xml.ws.Holder<com.deppon.esb.header.ESBHeader> esbHeader
    ) throws CommonException;
}
