package com.deppon.foss.module.advance.server.service.webservice._interface.finsyncarerrorservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.13
 * 2014-05-09T09:28:08.272+08:00
 * Generated source version: 2.6.13
 * 
 */
@WebService(targetNamespace = "http://www.deppon.com/foss/module/advance/server/service/webservice/interface/FinSynCarErrorService", name = "ISynCarErrorService")
@XmlSeeAlso({ObjectFactory.class, com.deppon.foss.module.advance.server.service.webservice.ObjectFactory.class, com.deppon.esb.header.ObjectFactory.class, com.deppon.esb.exception.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ISynCarErrorService {

    @WebResult(name = "synCarErrorRptResponse", targetNamespace = "http://www.deppon.com/foss/module/advance/server/service/webservice/", partName = "response")
    @WebMethod(action = "http://www.deppon.com/foss/module/advance/server/service/webservice/interface/FinSynCarErrorService")
    public SynCarErrorRptResponse synCarError(
        @WebParam(partName = "request", name = "synCarErrorRptRequest", targetNamespace = "http://www.deppon.com/foss/module/advance/server/service/webservice/")
        SynCarErrorRptRequest request,
        @WebParam(partName = "esbHeader", mode = WebParam.Mode.INOUT, name = "esbHeader", targetNamespace = "http://www.deppon.com/esb/header", header = true)
        javax.xml.ws.Holder<com.deppon.esb.header.ESBHeader> esbHeader
    ) throws CommException;
}
