
package com.deppon.foss.module.advance.server.service.webservice._interface.finsyncarerrorservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.13
 * 2014-05-09T09:28:08.202+08:00
 * Generated source version: 2.6.13
 * 
 */
public final class ISynCarErrorService_ISynCarErrorServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.deppon.com/foss/module/advance/server/service/webservice/interface/FinSynCarErrorService", "ISynCarErrorServiceService");

    private ISynCarErrorService_ISynCarErrorServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ISynCarErrorServiceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ISynCarErrorServiceService ss = new ISynCarErrorServiceService(wsdlURL, SERVICE_NAME);
        ISynCarErrorService port = ss.getISynCarErrorServicePort();  
        
        {
        System.out.println("Invoking synCarError...");
        com.deppon.foss.module.advance.server.service.webservice._interface.finsyncarerrorservice.SynCarErrorRptRequest _synCarError_request = null;
        com.deppon.esb.header.ESBHeader _synCarError_esbHeaderVal = new com.deppon.esb.header.ESBHeader();
        javax.xml.ws.Holder<com.deppon.esb.header.ESBHeader> _synCarError_esbHeader = new javax.xml.ws.Holder<com.deppon.esb.header.ESBHeader>(_synCarError_esbHeaderVal);
        try {
            com.deppon.foss.module.advance.server.service.webservice._interface.finsyncarerrorservice.SynCarErrorRptResponse _synCarError__return = port.synCarError(_synCarError_request, _synCarError_esbHeader);
            System.out.println("synCarError.result=" + _synCarError__return);

            System.out.println("synCarError._synCarError_esbHeader=" + _synCarError_esbHeader.value);
        } catch (CommException e) { 
            System.out.println("Expected exception: CommException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
