package com.deppon.nhr.module.remote.fssc.service.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import com.deppon.nhr.module.remote.fssc.service.PersonalLoanService;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.13
 * 2014-03-19T13:59:57.140+08:00
 * Generated source version: 2.6.13
 * 
 */
@WebServiceClient(name = "PersonalLoanServiceImplService", 
                  wsdlLocation = "http://10.224.72.141:8081/nhr/ws/personalLoanService?wsdl",
                  targetNamespace = "http://impl.service.fssc.remote.module.nhr.deppon.com/") 
public class PersonalLoanServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.service.fssc.remote.module.nhr.deppon.com/", "PersonalLoanServiceImplService");
    public final static QName PersonalLoanServiceImplPort = new QName("http://impl.service.fssc.remote.module.nhr.deppon.com/", "PersonalLoanServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://10.224.72.141:8081/nhr/ws/personalLoanService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PersonalLoanServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://10.224.72.141:8081/nhr/ws/personalLoanService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PersonalLoanServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PersonalLoanServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PersonalLoanServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns PersonalLoanService
     */
    @WebEndpoint(name = "PersonalLoanServiceImplPort")
    public PersonalLoanService getPersonalLoanServiceImplPort() {
        return super.getPort(PersonalLoanServiceImplPort, PersonalLoanService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PersonalLoanService
     */
    @WebEndpoint(name = "PersonalLoanServiceImplPort")
    public PersonalLoanService getPersonalLoanServiceImplPort(WebServiceFeature... features) {
        return super.getPort(PersonalLoanServiceImplPort, PersonalLoanService.class, features);
    }

}
